# bot のグローバルな値を入れておく


# ----------------------------------------------------------------------
# 基本的な設定はこちら
#

:account:         :tsukuba_gomi_bot
:debug_account:   :dev
:logfile:         tsukuba_gomi_bot.log
:logfile_debug:   tsukuba_gomi_bot_debug.log
:log_freq:        "monthly"
:log_level:       :INFO
:log_level_debug: :DEBUG


# ----------------------------------------------------------------------
# ゴミくじの出るもの
#

:gomikuji_item:
    # -
        # - 出やすさ
        # - 名称
    -
        - 15
        - :燃やせるごみ
    -
        - 15
        - :燃やせないごみ
    -
        - 5
        - :びん
    -
        - 5
        - :かん
    -
        - 5
        - :スプレー容器
    -
        - 15
        - :粗大ごみ
    -
        - 10
        - :古紙
    -
        - 10
        - :古布
    -
        - 1
        - :ごみの日bot(｀･ω･´)
    -
        - 5
        - :指定ごみ袋

