---
:account: :tsukuba_gomi_bot
:admin_screen_name:
    - "high_moctane"
:debug_account: :dev
:logfile: tsukuba_gomi_bot.log
:logfile_debug: tsukuba_gomi_bot_debug.log
:log_freq: monthly
:log_level: :INFO
:log_level_debug: :DEBUG
:limit_sec: 60.0
:limit_count: 10
:og_Internet: 5
:og_Tel: 2
:gomikuji_item:
- - 3
  - :燃やせるごみ
- - 3
  - :燃やせないごみ
- - 2
  - :びん
- - 2
  - :かん
- - 2
  - :スプレー容器
- - 3
  - :粗大ごみ
- - 3
  - :古紙
- - 3
  - :古布
- - 1
  - :ごみの日bot(｀･ω･´)
- - 1
  - :つくば市指定ごみ袋
