# bot のグローバルな値を入れておく


# ----------------------------------------------------------------------
# 基本的な設定はこちら
#

:account:         :tsukuba_gomi_bot
:debug_account:   :dev
:logfile:         tsukuba_gomi_bot.log
:logfile_debug:   tsukuba_gomi_bot_debug.log
:log_freq:        "monthly"
:log_level:       :INFO
:log_level_debug: :DEBUG

:limit_sec:       :300
:limit_count:     :20

# ----------------------------------------------------------------------
# ゴミくじの出るもの
#

:gomikuji_item:
    # -
        # - 出やすさ
        # - 名称
    -
        - 3
        - :燃やせるごみ
    -
        - 3
        - :燃やせないごみ
    -
        - 2
        - :びん
    -
        - 2
        - :かん
    -
        - 2
        - :スプレー容器
    -
        - 3
        - :粗大ごみ
    -
        - 3
        - :古紙
    -
        - 3
        - :古布
    -
        - 1
        - :ごみの日bot(｀･ω･´)
    -
        - 1
        - :つくば市指定ごみ袋

